# Generated by Django 4.2 on 2023-06-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('category', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('price_for_view', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, upload_to='products_images')),
            ],
        ),
    ]
