# Generated by Django 4.2 on 2023-06-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
