# Generated by Django 4.2 on 2023-06-30 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
    ]
